services:
  - type: web
    name: my-react-app
    runtime: static
    buildCommand: npm run build
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
